# Generated by Django 5.1.5 on 2025-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertg',
            name='userid',
            field=models.BigIntegerField(unique=True, verbose_name='id пользователя в телеграмм'),
        ),
    ]
