# Generated by Django 5.1.5 on 2025-02-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0007_alter_usertg_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertg',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='usertg',
            name='profile_create',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Создан ли профиль'),
        ),
    ]
