# Generated by Django 5.1.5 on 2025-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0008_usertg_birth_date_usertg_profile_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertg',
            name='profile_change',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Изменен ли профиль'),
        ),
        migrations.AlterField(
            model_name='cacthtg',
            name='fish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рыба'),
        ),
    ]
