# Generated by Django 5.1.5 on 2025-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0009_usertg_profile_change_alter_cacthtg_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacthtg',
            name='post_add',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Создан ли профиль'),
        ),
    ]
