# Generated by Django 5.1.5 on 2025-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0010_cacthtg_post_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacthtg',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=164, null=True),
        ),
        migrations.AddField(
            model_name='cacthtg',
            name='message_id',
            field=models.BigIntegerField(default=0, verbose_name='id сообщения пользователя в канале'),
        ),
    ]
