# Generated by Django 5.1.5 on 2025-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0011_cacthtg_image_hash_cacthtg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacthtg',
            name='post_add',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавлен улов в основную базу'),
        ),
    ]
