# Generated by Django 5.1.5 on 2025-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0013_remove_cacthtg_image_remove_cacthtg_image_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
