# Generated by Django 5.1.5 on 2025-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0014_alter_usertg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacthtg',
            name='message_id',
            field=models.TextField(default='0', verbose_name='id сообщения пользователя в канале'),
        ),
    ]
