# Generated by Django 5.1.5 on 2025-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageappfish', '0015_alter_cacthtg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertg',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='номер телефона в телеграмм'),
        ),
    ]
