# Generated by Django 5.1.5 on 2025-02-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('threshold_small', models.IntegerField(help_text='Вес в гр.ниже этого значения - маленькая', verbose_name='Порог для маленькой рыбы')),
                ('threshold_medium', models.IntegerField(help_text='Вес в гр. ниже этого значения - средняя', verbose_name='Порог для средней рыбы')),
                ('threshold_big', models.IntegerField(help_text='Вес в гр. ниже этого значения - большая', verbose_name='Порог для большой рыбы')),
                ('threshold_trophy', models.IntegerField(help_text='Вес в гр. ниже этого значения - трофейная', verbose_name='Порог для трофейной рыбы')),
                ('point', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вид рыбы',
                'verbose_name_plural': 'Виды рыб',
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('fishing_rod', 'Балонское Удилище'), ('swing_rod', 'Маховое Удилище'), ('mast_rod', 'Матчевое Удилище'), ('feeder_rod', 'Фидерное Удилище'), ('spining_rod', 'Спининговое Удилище'), ('casting_rod', 'Кастинговое Удилище'), ('whip_rod', 'Нахлыстовое Удилище'), ('winter_rod', 'Зимнее Удилище'), ('circle_gear', 'кружок-жерлица'), ('gun', 'Ружьё')], max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('floater', 'поплавочный'), ('feeder', 'фидерный'), ('spining_tvetcheng', 'твитчинг'), ('artificial_lures', 'искуственные приманки'), ('whip', 'Нахлыст'), ('low', 'Донка'), ('troling', 'Тролинг'), ('casting', 'Кастинг'), ('winter', 'Зимняя'), ('fish', 'Живец'), ('spearfishing ', 'Подводная охота')], max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_geo', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Размер')),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catch/')),
                ('date_catch', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishman_catch', to=settings.AUTH_USER_MODEL)),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_catch', to='appfish.fish', verbose_name='Вид рыбы')),
                ('location_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appfish.place')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('alias', models.TextField(blank=True, null=True, verbose_name='Псевдоним')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('gear_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gear', to='appfish.gear', verbose_name='Основкая снасть')),
                ('metod_catch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metod', to='appfish.method', verbose_name='основной метод ловли')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
