# Generated by Django 5.1.5 on 2025-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
