# Generated by Django 5.1.5 on 2025-02-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0002_alter_fish_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
