# Generated by Django 5.1.5 on 2025-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0003_alter_gear_name_alter_method_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='threshold_big',
            field=models.FloatField(help_text='Вес в гр. ниже этого значения - большая', verbose_name='Порог для большой рыбы'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='threshold_medium',
            field=models.FloatField(help_text='Вес в гр. ниже этого значения - средняя', verbose_name='Порог для средней рыбы'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='threshold_small',
            field=models.FloatField(help_text='Вес в гр.ниже этого значения - маленькая', verbose_name='Порог для маленькой рыбы'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='threshold_trophy',
            field=models.FloatField(help_text='Вес в гр. ниже этого значения - трофейная', verbose_name='Порог для трофейной рыбы'),
        ),
    ]
