# Generated by Django 5.1.5 on 2025-02-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0004_alter_fish_threshold_big_alter_fish_threshold_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='baitfish',
            field=models.FloatField(default=1, help_text='Вес в гр.ниже этого значения - живец', verbose_name='Порог для живца'),
        ),
    ]
