# Generated by Django 5.1.5 on 2025-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0005_fish_baitfish'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=164, null=True),
        ),
    ]
