# Generated by Django 5.1.5 on 2025-03-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfish', '0006_catch_image_hash'),
        ('manageappfish', '0013_remove_cacthtg_image_remove_cacthtg_image_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='image_hash',
        ),
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_image_catch', to='manageappfish.cacthtgimage', verbose_name='Основное фото'),
        ),
    ]
